	class ABTM_AntiAirWDL: I_Soldier_AA_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_AntiAirWDL";
		scope=2;
		displayName="Aggressor Woodland (AA)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"cwr3_launch_redeye_loaded",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"cwr3_launch_redeye_loaded",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_AntiTankWDL: I_Soldier_LAT_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_AntiTankWDL";
		scope=2;
		displayName="Aggressor Woodland (AT)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"launch_MRAWS_green_rail_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"launch_MRAWS_green_rail_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_AutoriflemanWDL: I_Soldier_AR_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_AutoriflemanWDL";
		scope=2;
		displayName="Aggressor Woodland (AR)";
		weapons[]=
		{
			"CUP_lmg_M249_E1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_lmg_M249_E1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_CrewmanWDL: I_crew_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_CrewmanWDL";
		scope=2;
		displayName="Aggressor Woodland (Crew)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShellPurple",
			"SmokeShellYellow",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShellPurple",
			"SmokeShellYellow",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_SLA_TankerHelmet",
			"SP_Balaclava_Skull2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_SLA_TankerHelmet",
			"SP_Balaclava_Skull2",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_FieldUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_DMRWDL: I_Soldier_M_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_DMRWDL";
		scope=2;
		displayName="Aggressor Woodland (DMR)";
		weapons[]=
		{
			"ABTM_M14_ScopedMagnified",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ABTM_M14_ScopedMagnified",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_20Rnd_762x51_DMR",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_adf",
			"H_Booniehat_khk_hs",
			"VSM_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_adf",
			"H_Booniehat_khk_hs",
			"VSM_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_DMRAssistWDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_DMRAssistWDL";
		scope=2;
		displayName="Aggressor Woodland (DMR Asst.)";
		weapons[]=
		{
			"CUP_arifle_M16A1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_adf",
			"H_Booniehat_khk_hs",
			"CFP_Shemagh_Face_Flecktarn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_adf",
			"H_Booniehat_khk_hs",
			"CFP_Shemagh_Face_Flecktarn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_DriverWDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_DriverWDL";
		scope=2;
		displayName="Aggressor Woodland (Driver)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_USArmy_HelmetACH_UCP",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_USArmy_HelmetACH_UCP",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_EngineerWDL: I_engineer_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_EngineerWDL";
		scope=2;
		displayName="Aggressor Woodland (Engineer)";
		weapons[]=
		{
			"CUP_arifle_M16A1",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A1",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_20Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_MachinegunnerWDL: I_Soldier_AR_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_MachinegunnerWDL";
		scope=2;
		displayName="Aggressor Woodland (MG)";
		weapons[]=
		{
			"ABTM_Minimi",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ABTM_Minimi",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "ADFU_200Rnd_556x45",
			"ADFU_200Rnd_556x45",
			"ADFU_200Rnd_556x45",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "ADFU_200Rnd_556x45",
			"ADFU_200Rnd_556x45",
			"ADFU_200Rnd_556x45",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_MachinegunnerAssistWDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_MachinegunnerAssistWDL";
		scope=2;
		displayName="Aggressor Woodland (MG Asst.)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_RadiomanWDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		backpack="ABTM_Main_Radiopack";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_RadiomanWDL";
		scope=2;
		displayName="Aggressor Woodland (Radioman)";
		weapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_Colt727",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_adf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_adf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_RiflemanWDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_RiflemanWDL";
		scope=2;
		displayName="Aggressor Woodland (Rifleman)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92_GG",
			"VSM_balaclava2_Black",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_RiflemanRPG1WDL: I_Soldier_LAT_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		backpack="ABTM_Misc_RPGs1";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_RiflemanRPG1WDL";
		scope=2;
		displayName="Aggressor Woodland (Rifleman, RPG 1)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"CUP_launch_RPG18_Loaded",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"CUP_launch_RPG18_Loaded",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_RiflemanRPG2WDL: I_Soldier_LAT_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		backpack="ABTM_Misc_RPGs2";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_RiflemanRPG2WDL";
		scope=2;
		displayName="Aggressor Woodland (Rifleman, RPG 2)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"CUP_launch_RPG18_Loaded",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"CUP_launch_RPG18_Loaded",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_Sentry1WDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_Sentry1WDL";
		scope=2;
		displayName="Aggressor Woodland (Sentry 1)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_US_patrol_cap_WDL",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SP_Tactical1_Green",
			"CUP_H_US_patrol_cap_WDL",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_Sentry2WDL: I_Soldier_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_Sentry2WDL";
		scope=2;
		displayName="Aggressor Woodland (Sentry 2)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"H_Booniehat_khk",
			"CUP_PMC_Facewrap_Tropical",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf",
			"H_Booniehat_khk",
			"CUP_PMC_Facewrap_Tropical",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_SquadLeaderWDL: I_Soldier_SL_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_SquadLeaderWDL";
		scope=2;
		displayName="Aggressor Woodland (Squad Leader)";
		weapons[]=
		{
			"CUP_arifle_M16A2_GL",
			"CUP_hgun_M9",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2_GL",
			"CUP_hgun_M9",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShellRed",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShellRed",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Peltor_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Peltor_Goggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};
	class ABTM_TeamLeaderWDL: I_Soldier_TL_F
	{
		side=2;
		faction="ABTM_Redland_Aggressors";
		vehicleclass="ABTM_Infantry";
		identityTypes[]=
		{
			"NoGlasses",
		};
		author="Ashton";
		_generalMacro="ABTM_TeamLeaderWDL";
		scope=2;
		displayName="Aggressor Woodland (Team Leader)";
		weapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"CUP_arifle_M16A2",
			"Throw",
			"Put"
		};
		magazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShellRed",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
            "CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_30Rnd_556x45_Stanag",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A1_HE",
			"SmokeShellRed",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"ake_ilbv_sbo3_inf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Peltor",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"ake_ilbv_sbo3_inf_sc",
			"CUP_H_Ger_M92",
			"VSM_Balaclava2_black_Peltor",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		uniformClass="CFP_U_BattleDressUniform_woodlanddark";
		camouflage=1.6;
	};